name: HiFiNi 自动签到
 
on:
    push:
        branches:
            - master
    schedule:
        - cron: '1 16 * * *'  # 北京时间 00:01

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v3
            - name: Set go
              uses: actions/setup-go@v3
              with:
                go-version: '^1.22'
            - name: HIFINI 自动签到
              env:
                COOKIES: ${{ secrets.COOKIES }}
                TG_TOKEN: ${{ secrets.TG_TOKEN }}
                TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
              run: go run main.go
